# Generated by Django 2.2.6 on 2019-11-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalcourseitem',
            options={'ordering': ['course', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='itemheading',
            options={'ordering': ['course', 'type', 'order', 'text']},
        ),
        migrations.RenameField(
            model_name='itemheading',
            old_name='name',
            new_name='text',
        ),
    ]
