# Generated by Django 2.2.6 on 2019-10-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ['course', 'type', 'order', 'name']},
        ),
    ]
