# Generated by Django 2.2.6 on 2019-11-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191112_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemheading',
            options={'ordering': ['course', 'type', 'order', 'name']},
        ),
        migrations.RenameField(
            model_name='itemheading',
            old_name='text',
            new_name='name',
        ),
    ]
