# Generated by Django 2.2.6 on 2019-11-15 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20191112_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalcourseitem',
            options={'ordering': ['course']},
        ),
        migrations.AlterModelOptions(
            name='itemheading',
            options={'ordering': ['course', 'type']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalcourseitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemheading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
