# Generated by Django 2.2.6 on 2019-11-04 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191102_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category or heading that this item will apear under. Leave blank to simply appear at the top.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.ItemCategory'),
        ),
        migrations.AlterField(
            model_name='generalcourseitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category or heading that this item will apear under. Leave blank to simply appear at the top.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.ItemCategory'),
        ),
    ]
