# Generated by Django 2.2.6 on 2019-11-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191115_0359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemheading',
            options={'ordering': ['course']},
        ),
        migrations.RemoveField(
            model_name='itemheading',
            name='type',
        ),
    ]
