# Generated by Django 2.2.6 on 2019-11-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20191117_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemheading',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
