# Generated by Django 2.2.6 on 2019-11-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_itemheading_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='content_type',
            field=models.CharField(choices=[('U', 'URL'), ('M', 'Markdown-formatted Text')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='generalcourseitem',
            name='content_type',
            field=models.CharField(choices=[('U', 'URL'), ('M', 'Markdown-formatted Text')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content_type',
            field=models.CharField(choices=[('U', 'URL'), ('M', 'Markdown-formatted Text')], default='M', max_length=1),
        ),
    ]
