# Generated by Django 2.2.6 on 2019-11-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20191121_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralCourseItem',
            new_name='CourseItem',
        ),
    ]
