# Generated by Django 2.2.6 on 2019-11-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20191122_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='url_content',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='url_content',
        ),
    ]
