# Generated by Django 2.2.6 on 2019-11-12 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verification_code', models.CharField(max_length=43, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, help_text='Enter a nickname you prefer to go by. If provided, your nickname will be displayed instead of your real name on BCM courses, though instructors can still look your real name up if they choose.', max_length=20)),
                ('institution_id', models.CharField(blank=True, help_text='If you would like to associate your account with an existing ID at another institution, enter it here.', max_length=100)),
            ],
        ),
    ]
