# Generated by Django 2.2.6 on 2019-10-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(max_length=43, null=True, unique=True),
        ),
    ]
