# Generated by Django 2.2.6 on 2019-10-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20191023_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(default='', max_length=43),
        ),
    ]
