# Generated by Django 2.2.6 on 2019-10-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20191023_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(max_length=43, unique=True),
        ),
    ]
