# Generated by Django 2.2.6 on 2019-11-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20191023_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution_id',
            field=models.CharField(blank=True, help_text='If you would like to associate your account with an existing ID at another institution, enter it here.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, help_text='Enter a nickname you prefer to go by. If provided, your nickname will be displayed instead of your real name on BCM courses, though instructors can still look your real name up if they choose.', max_length=20),
        ),
    ]
